export const recipeData = {
  buildings: [
    { name: 'Assembler', power: -15, category: 'Production', cost: {'Reinforced Iron Plate': 8, 'Rotor': 4, 'Cable': 20} },
    { name: 'Biomass Burner', power: 30, category: 'Power', cost: {'Iron Plate': 15, 'Iron Rod': 15, 'Wire': 25} },
    { name: 'Blender', power: -75, category: 'Production', cost: {'Motor': 10, 'Heavy Modular Frame': 3, 'Aluminum Casing': 50} },
    { name: 'Coal Generator', power: 75, category: 'Power', cost: {'Reinforced Iron Plate': 20, 'Rotor': 10, 'Cable': 30} },
    { name: 'Constructor', power: -4, category: 'Production', cost: {'Reinforced Iron Plate': 2, 'Cable': 8} },
    { name: 'Converter', power: -100, category: 'Production', cost: {'Heavy Modular Frame': 20, 'Computer': 10, 'High-Speed Connector': 100} },
    { name: 'Foundry', power: -16, category: 'Production', cost: {'Modular Frame': 10, 'Concrete': 25} },
    { name: 'Fuel Generator', power: 250, category: 'Power', cost: {'Computer': 5, 'Heavy Modular Frame': 15, 'Rubber': 50, 'Quickwire': 50} },
    { name: 'Geothermal Generator', power: 200, category: 'Power', cost: {'Supercomputer': 3, 'Heavy Modular Frame': 10, 'Rotor': 20} },
    { name: 'Manufacturer', power: -55, category: 'Production', cost: {'Heavy Modular Frame': 5, 'Motor': 10, 'Cable': 100, 'Computer': 2} },
    { name: 'Miner Mk.1', power: -5, category: 'Extraction', cost: {'Iron Plate': 10, 'Iron Rod': 10, 'Concrete': 10} },
    { name: 'Miner Mk.2', power: -12, category: 'Extraction', cost: {'Steel Pipe': 10, 'Encased Industrial Beam': 10, 'Motor': 4} },
    { name: 'Miner Mk.3', power: -30, category: 'Extraction', cost: {'Supercomputer': 1, 'Heavy Modular Frame': 5, 'Steel Pipe': 20} },
    { name: 'Nuclear Power Plant', power: 2500, category: 'Power', cost: {'Supercomputer': 25, 'Heavy Modular Frame': 100, 'Concrete': 500} },
    { name: 'Oil Extractor', power: -40, category: 'Extraction', cost: {'Motor': 10, 'Encased Industrial Beam': 20, 'Circuit Board': 15} },
    { name: 'Packager', power: -10, category: 'Production', cost: {'Plastic': 10, 'Rubber': 10, 'Steel Beam': 5} },
    { name: 'Particle Accelerator', power: -250, category: 'Production', cost: {'Radio Control Unit': 10, 'Supercomputer': 3, 'Electromagnetic Control Rod': 50} },
    { name: 'Quantum Encoder', power: -1000, category: 'Production', cost: {'AI Expansion Server': 1, 'Superposition Oscillator': 5, 'Neural-Quantum Processor': 5} },
    { name: 'Refinery', power: -30, category: 'Production', cost: {'Steel Pipe': 15, 'Motor': 5, 'Computer': 3} },
    { name: 'Resource Well Extractor', power: -150, category: 'Extraction', cost: {'Heavy Modular Frame': 10, 'Computer': 2, 'Motor': 20} },
    { name: 'Smelter', power: -4, category: 'Production', cost: {'Iron Rod': 8, 'Wire': 10} },
    { name: 'Water Extractor', power: -20, category: 'Extraction', cost: {'Copper Sheet': 20, 'Reinforced Iron Plate': 10, 'Rotor': 5} }
  ],
  recipes: {
    'Constructor': [
      {name: 'Alien DNA Capsule', inputs: {'Alien Protein': 10}, outputs: {'Alien DNA Capsule': 10}},
      {name: 'Aluminum Casing', inputs: {'Aluminum Ingot': 90}, outputs: {'Aluminum Casing': 60}},
      {name: 'Biomass (Alien Protein)', inputs: {'Alien Protein': 15}, outputs: {'Biomass': 1500}},
      {name: 'Biomass (Leaves)', inputs: {'Leaves': 120}, outputs: {'Biomass': 60}},
      {name: 'Biomass (Mycelia)', inputs: {'Mycelia': 15}, outputs: {'Biomass': 150}},
      {name: 'Biomass (Wood)', inputs: {'Wood': 60}, outputs: {'Biomass': 300}},
      {name: 'Cable', inputs: {'Wire': 60}, outputs: {'Cable': 30}},
      {name: 'Concrete', inputs: {'Limestone': 45}, outputs: {'Concrete': 15}},
      {name: 'Copper Powder', inputs: {'Copper Ingot': 300}, outputs: {'Copper Powder': 50}},
      {name: 'Copper Sheet', inputs: {'Copper Ingot': 20}, outputs: {'Copper Sheet': 10}},
      {name: 'Empty Canister', inputs: {'Plastic': 30}, outputs: {'Empty Canister': 60}},
      {name: 'Empty Fluid Tank', inputs: {'Aluminum Ingot': 60}, outputs: {'Empty Fluid Tank': 60}},
      {name: 'Ficsite Trigon', inputs: {'Ficsite Ingot': 10}, outputs: {'Ficsite Trigon': 30}},
      {name: 'Hatcher Protein', inputs: {'Hatcher Remains': 20}, outputs: {'Alien Protein': 20}},
      {name: 'Hog Protein', inputs: {'Hog Remains': 20}, outputs: {'Alien Protein': 20}},
      {name: 'Iron Plate', inputs: {'Iron Ingot': 30}, outputs: {'Iron Plate': 20}},
      {name: 'Iron Rebar', inputs: {'Iron Rod': 15}, outputs: {'Iron Rebar': 15}},
      {name: 'Iron Rod', inputs: {'Iron Ingot': 15}, outputs: {'Iron Rod': 15}},
      {name: 'Power Shard (1)', inputs: {'Blue Power Slug': 7.5}, outputs: {'Power Shard': 7.5}},
      {name: 'Power Shard (2)', inputs: {'Yellow Power Slug': 5}, outputs: {'Power Shard': 10}},
      {name: 'Power Shard (5)', inputs: {'Purple Power Slug': 2.5}, outputs: {'Power Shard': 12.5}},
      {name: 'Quartz Crystal', inputs: {'Raw Quartz': 37.5}, outputs: {'Quartz Crystal': 22.5}},
      {name: 'Quickwire', inputs: {'Caterium Ingot': 12}, outputs: {'Quickwire': 60}},
      {name: 'Reanimated SAM', inputs: {'SAM': 120}, outputs: {'Reanimated SAM': 30}},
      {name: 'Screw', inputs: {'Iron Rod': 10}, outputs: {'Screw': 40}},
      {name: 'Shatter Rebar', inputs: {'Iron Rebar': 10}, outputs: {'Shatter Rebar': 5}},
      {name: 'Silica', inputs: {'Raw Quartz': 22.5}, outputs: {'Silica': 37.5}},
      {name: 'Solid Biofuel', inputs: {'Biomass': 120}, outputs: {'Solid Biofuel': 60}},
      {name: 'Spitter Protein', inputs: {'Spitter Remains': 20}, outputs: {'Alien Protein': 20}},
      {name: 'Steel Beam', inputs: {'Steel Ingot': 60}, outputs: {'Steel Beam': 15}},
      {name: 'Steel Pipe', inputs: {'Steel Ingot': 30}, outputs: {'Steel Pipe': 20}},
      {name: 'Stinger Protein', inputs: {'Stinger Remains': 20}, outputs: {'Alien Protein': 20}},
      {name: 'Stun Rebar', inputs: {'Iron Rebar': 10}, outputs: {'Stun Rebar': 5}},
      {name: 'Wire', inputs: {'Copper Ingot': 15}, outputs: {'Wire': 30}},
      {name: 'Cast Screw', inputs: {'Iron Ingot': 12.5}, outputs: {'Screw': 50}, isAlternate: true},
      {name: 'Iron Pipe', inputs: {'Iron Ingot': 100}, outputs: {'Steel Pipe': 25}, isAlternate: true},
      {name: 'Iron Wire', inputs: {'Iron Ingot': 12.5}, outputs: {'Wire': 22.5}, isAlternate: true},
      {name: 'Steel Rod', inputs: {'Steel Ingot': 12}, outputs: {'Iron Rod': 48}, isAlternate: true}
    ],
    'Smelter': [
      {name: 'Caterium Ingot', inputs: {'Caterium Ore': 45}, outputs: {'Caterium Ingot': 15}},
      {name: 'Copper Ingot', inputs: {'Copper Ore': 30}, outputs: {'Copper Ingot': 30}},
      {name: 'Iron Ingot', inputs: {'Iron Ore': 30}, outputs: {'Iron Ingot': 30}},
      {name: 'Pure Aluminum Ingot', inputs: {'Aluminum Scrap': 60}, outputs: {'Aluminum Ingot': 30}, isAlternate: true}
    ],
    'Foundry': [
      {name: 'Aluminum Ingot', inputs: {'Aluminum Scrap': 90, 'Silica': 75}, outputs: {'Aluminum Ingot': 60}},
      {name: 'Steel Ingot', inputs: {'Iron Ore': 45, 'Coal': 45}, outputs: {'Steel Ingot': 45}},
      {name: 'Basic Iron Ingot', inputs: {'Iron Ore': 25, 'Limestone': 40}, outputs: {'Iron Ingot': 50}, isAlternate: true},
      {name: 'Coke Steel Ingot', inputs: {'Iron Ore': 75, 'Petroleum Coke': 75}, outputs: {'Steel Ingot': 100}, isAlternate: true},
      {name: 'Compacted Steel Ingot', inputs: {'Iron Ore': 5, 'Compacted Coal': 2.5}, outputs: {'Steel Ingot': 10}, isAlternate: true},
      {name: 'Copper Alloy Ingot', inputs: {'Copper Ore': 50, 'Iron Ore': 50}, outputs: {'Copper Ingot': 100}, isAlternate: true},
      {name: 'Fused Quartz Crystal', inputs: {'Raw Quartz': 75, 'Coal': 36}, outputs: {'Quartz Crystal': 54}, isAlternate: true},
      {name: 'Iron Alloy Ingot', inputs: {'Iron Ore': 40, 'Copper Ore': 10}, outputs: {'Iron Ingot': 75}, isAlternate: true},
      {name: 'Molded Beam', inputs: {'Steel Ingot': 120, 'Concrete': 80}, outputs: {'Steel Beam': 45}, isAlternate: true},
      {name: 'Molded Steel Pipe', inputs: {'Steel Ingot': 50, 'Concrete': 30}, outputs: {'Steel Pipe': 50}, isAlternate: true},
      {name: 'Solid Steel Ingot', inputs: {'Iron Ingot': 40, 'Coal': 40}, outputs: {'Steel Ingot': 60}, isAlternate: true},
      {name: 'Steel Cast Plate', inputs: {'Iron Ingot': 15, 'Steel Ingot': 15}, outputs: {'Iron Plate': 45}, isAlternate: true},
      {name: 'Tempered Caterium Ingot', inputs: {'Caterium Ore': 45, 'Petroleum Coke': 15}, outputs: {'Caterium Ingot': 22.5}, isAlternate: true},
      {name: 'Tempered Copper Ingot', inputs: {'Copper Ore': 25, 'Petroleum Coke': 40}, outputs: {'Copper Ingot': 60}, isAlternate: true}
    ],
    'Assembler': [
      {name: 'AI Limiter', inputs: {'Copper Sheet': 25, 'Quickwire': 100}, outputs: {'AI Limiter': 5}},
      {name: 'Alclad Aluminum Sheet', inputs: {'Aluminum Ingot': 30, 'Copper Ingot': 10}, outputs: {'Alclad Aluminum Sheet': 30}},
      {name: 'Assembly Director System', inputs: {'Adaptive Control Unit': 1.5, 'Supercomputer': 0.75}, outputs: {'Assembly Director System': 0.75}},
      {name: 'Automated Wiring', inputs: {'Stator': 2.5, 'Cable': 50}, outputs: {'Automated Wiring': 2.5}},
      {name: 'Black Powder', inputs: {'Coal': 15, 'Sulfur': 15}, outputs: {'Black Powder': 30}},
      {name: 'Circuit Board', inputs: {'Copper Sheet': 15, 'Plastic': 30}, outputs: {'Circuit Board': 7.5}},
      {name: 'Cluster Nobelisk', inputs: {'Nobelisk': 7.5, 'Smokeless Powder': 10}, outputs: {'Cluster Nobelisk': 2.5}},
      {name: 'Compacted Coal', inputs: {'Coal': 25, 'Sulfur': 25}, outputs: {'Compacted Coal': 25}, isAlternate: true},
      {name: 'Electromagnetic Control Rod', inputs: {'Stator': 6, 'AI Limiter': 4}, outputs: {'Electromagnetic Control Rod': 4}},
      {name: 'Encased Industrial Beam', inputs: {'Steel Beam': 18, 'Concrete': 36}, outputs: {'Encased Industrial Beam': 6}},
      {name: 'Encased Plutonium Cell', inputs: {'Plutonium Pellet': 10, 'Concrete': 20}, outputs: {'Encased Plutonium Cell': 5}},
      {name: 'Fabric', inputs: {'Mycelia': 15, 'Biomass': 75}, outputs: {'Fabric': 15}},
      {name: 'Fancy Fireworks', inputs: {'FICSMAS Tree Branch': 10, 'FICSMAS Bow': 7.5}, outputs: {'Fancy Fireworks': 2.5}},
      {name: 'Gas Nobelisk', inputs: {'Nobelisk': 5, 'Biomass': 50}, outputs: {'Gas Nobelisk': 5}},
      {name: 'Heat Sink', inputs: {'Alclad Aluminum Sheet': 37.5, 'Copper Sheet': 22.5}, outputs: {'Heat Sink': 7.5}},
      {name: 'Homing Rifle Ammo', inputs: {'Rifle Ammo': 50, 'High-Speed Connector': 2.5}, outputs: {'Homing Rifle Ammo': 25}},
      {name: 'Magnetic Field Generator', inputs: {'Versatile Framework': 2.5, 'Electromagnetic Control Rod': 1}, outputs: {'Magnetic Field Generator': 1}},
      {name: 'Modular Frame', inputs: {'Reinforced Iron Plate': 3, 'Iron Rod': 12}, outputs: {'Modular Frame': 2}},
      {name: 'Motor', inputs: {'Rotor': 10, 'Stator': 10}, outputs: {'Motor': 5}},
      {name: 'Nobelisk', inputs: {'Black Powder': 20, 'Steel Pipe': 20}, outputs: {'Nobelisk': 10}},
      {name: 'Pressure Conversion Cube', inputs: {'Fused Modular Frame': 1, 'Radio Control Unit': 2}, outputs: {'Pressure Conversion Cube': 1}},
      {name: 'Pulse Nobelisk', inputs: {'Nobelisk': 5, 'Crystal Oscillator': 1}, outputs: {'Pulse Nobelisk': 5}},
      {name: 'Reinforced Iron Plate', inputs: {'Iron Plate': 30, 'Screw': 60}, outputs: {'Reinforced Iron Plate': 5}},
      {name: 'Rifle Ammo', inputs: {'Copper Sheet': 15, 'Smokeless Powder': 10}, outputs: {'Rifle Ammo': 15}},
      {name: 'Rotor', inputs: {'Iron Rod': 20, 'Screw': 100}, outputs: {'Rotor': 4}},
      {name: 'Smart Plating', inputs: {'Reinforced Iron Plate': 2, 'Rotor': 2}, outputs: {'Smart Plating': 2}},
      {name: 'Stator', inputs: {'Steel Pipe': 15, 'Wire': 40}, outputs: {'Stator': 5}},
      {name: 'Versatile Framework', inputs: {'Modular Frame': 2.5, 'Steel Beam': 30}, outputs: {'Versatile Framework': 5}},
      {name: 'Adhered Iron Plate', inputs: {'Iron Plate': 11.25, 'Rubber': 3.75}, outputs: {'Reinforced Iron Plate': 3.75}, isAlternate: true},
      {name: 'Bolted Frame', inputs: {'Reinforced Iron Plate': 7.5, 'Screw': 140}, outputs: {'Modular Frame': 5}, isAlternate: true},
      {name: 'Stitched Iron Plate', inputs: {'Iron Plate': 18.75, 'Wire': 75}, outputs: {'Reinforced Iron Plate': 5.625}, isAlternate: true},
      {name: 'Steel Rotor', inputs: {'Steel Pipe': 10, 'Wire': 30}, outputs: {'Rotor': 5}, isAlternate: true},
      {name: 'Caterium Circuit Board', inputs: {'Plastic': 12.5, 'Quickwire': 37.5}, outputs: {'Circuit Board': 8.75}, isAlternate: true},
      {name: 'Coated Iron Plate', inputs: {'Iron Ingot': 50, 'Plastic': 10}, outputs: {'Iron Plate': 75}, isAlternate: true},
      {name: 'Encased Industrial Pipe', inputs: {'Steel Pipe': 28, 'Concrete': 20}, outputs: {'Encased Industrial Beam': 4}, isAlternate: true},
      {name: 'OC Supercomputer', inputs: {'Radio Control Unit': 6, 'Cooling System': 6}, outputs: {'Supercomputer': 3}, isAlternate: true}
    ],
    'Manufacturer': [
      {name: 'Adaptive Control Unit', inputs: {'Automated Wiring': 5, 'Circuit Board': 5, 'Heavy Modular Frame': 1, 'Computer': 2}, outputs: {'Adaptive Control Unit': 1}},
      {name: 'Ballistic Warp Drive', inputs: {'Thermal Propulsion Rocket': 1, 'Singularity Cell': 5, 'Superposition Oscillator': 2, 'Dark Matter Crystal': 40}, outputs: {'Ballistic Warp Drive': 1}},
      {name: 'Computer', inputs: {'Circuit Board': 10, 'Cable': 20, 'Plastic': 40}, outputs: {'Computer': 2.5}},
      {name: 'Crystal Oscillator', inputs: {'Quartz Crystal': 18, 'Cable': 14, 'Reinforced Iron Plate': 2.5}, outputs: {'Crystal Oscillator': 1}},
      {name: 'Explosive Rebar', inputs: {'Iron Rebar': 10, 'Smokeless Powder': 10, 'Steel Pipe': 10}, outputs: {'Explosive Rebar': 5}},
      {name: 'Gas Filter', inputs: {'Fabric': 15, 'Coal': 30, 'Iron Plate': 15}, outputs: {'Gas Filter': 7.5}},
      {name: 'Heavy Modular Frame', inputs: {'Modular Frame': 10, 'Steel Pipe': 40, 'Encased Industrial Beam': 10, 'Screw': 240}, outputs: {'Heavy Modular Frame': 2}},
      {name: 'High-Speed Connector', inputs: {'Quickwire': 210, 'Cable': 37.5, 'Circuit Board': 3.75}, outputs: {'High-Speed Connector': 3.75}},
      {name: 'Iodine-Infused Filter', inputs: {'Gas Filter': 3.75, 'Quickwire': 30, 'Aluminum Casing': 3.75}, outputs: {'Iodine-Infused Filter': 3.75}},
      {name: 'Modular Engine', inputs: {'Motor': 2, 'Rubber': 15, 'Smart Plating': 2}, outputs: {'Modular Engine': 1}},
      {name: 'Nuke Nobelisk', inputs: {'Nobelisk': 2.5, 'Encased Uranium Cell': 10, 'Smokeless Powder': 5, 'AI Limiter': 3}, outputs: {'Nuke Nobelisk': 0.5}},
      {name: 'Plutonium Fuel Rod', inputs: {'Encased Plutonium Cell': 7.5, 'Steel Beam': 4.5, 'Electromagnetic Control Rod': 1.5, 'Heat Sink': 2.5}, outputs: {'Plutonium Fuel Rod': 0.25}},
      {name: 'Radio Control Unit', inputs: {'Aluminum Casing': 40, 'Crystal Oscillator': 1.25, 'Computer': 2.5}, outputs: {'Radio Control Unit': 2.5}},
      {name: 'SAM Fluctuator', inputs: {'Reanimated SAM': 60, 'Wire': 50, 'Steel Pipe': 30}, outputs: {'SAM Fluctuator': 10}},
      {name: 'Singularity Cell', inputs: {'Nuclear Pasta': 1, 'Dark Matter Crystal': 20, 'Iron Plate': 100, 'Concrete': 200}, outputs: {'Singularity Cell': 10}},
      {name: 'Supercomputer', inputs: {'Computer': 7.5, 'AI Limiter': 3.75, 'High-Speed Connector': 5.625, 'Plastic': 52.5}, outputs: {'Supercomputer': 1.875}},
      {name: 'Thermal Propulsion Rocket', inputs: {'Modular Engine': 2.5, 'Turbo Motor': 1, 'Cooling System': 3, 'Fused Modular Frame': 1}, outputs: {'Thermal Propulsion Rocket': 1}},
      {name: 'Turbo Motor', inputs: {'Cooling System': 7.5, 'Radio Control Unit': 3.75, 'Motor': 7.5, 'Rubber': 45}, outputs: {'Turbo Motor': 1.875}},
      {name: 'Uranium Fuel Rod', inputs: {'Encased Uranium Cell': 20, 'Encased Industrial Beam': 1.2, 'Electromagnetic Control Rod': 2}, outputs: {'Uranium Fuel Rod': 0.4}},
      {name: 'Automated Speed Wiring', inputs: {'Stator': 3.75, 'Wire': 75, 'High-Speed Connector': 1.875}, outputs: {'Automated Wiring': 7.5}, isAlternate: true},
      {name: 'Caterium Computer', inputs: {'Circuit Board': 7, 'Quickwire': 28, 'Rubber': 12}, outputs: {'Computer': 1}, isAlternate: true},
      {name: 'Heavy Encased Frame', inputs: {'Modular Frame': 7.5, 'Encased Industrial Beam': 9.375, 'Steel Pipe': 33.75, 'Concrete': 20.625}, outputs: {'Heavy Modular Frame': 2.8125}, isAlternate: true},
      {name: 'Insulated Crystal Oscillator', inputs: {'Quartz Crystal': 18.75, 'Rubber': 11.25, 'AI Limiter': 1.875}, outputs: {'Crystal Oscillator': 1.875}, isAlternate: true},
      {name: 'Radio Control System', inputs: {'Crystal Oscillator': 1.5, 'Circuit Board': 15, 'Aluminum Casing': 90, 'Rubber': 45}, outputs: {'Radio Control Unit': 4.5}, isAlternate: true},
      {name: 'Turbo Electric Motor', inputs: {'Motor': 6.5625, 'Radio Control Unit': 8.4375, 'Electromagnetic Control Rod': 4.6875, 'Rotor': 6.5625}, outputs: {'Turbo Motor': 2.8125}, isAlternate: true},
      {name: 'Rigour Motor', inputs: {'Crystal Oscillator': 1.875, 'Stator': 3.75}, outputs: {'Motor': 3.75}, isAlternate: true},
      {name: 'Super-State Computer', inputs: {'Computer': 3.6, 'AI Limiter': 2.4, 'Crystal Oscillator': 1.2}, outputs: {'Supercomputer': 2.4}, isAlternate: true},
      {name: 'Classic Battery', inputs: {'Sulfur': 45, 'Alclad Aluminum Sheet': 52.5, 'Plastic': 60, 'Wire': 90}, outputs: {'Battery': 30}, isAlternate: true}
    ],
    'Refinery': [
      {name: 'Alumina Solution', inputs: {'Bauxite': 120, 'Water': 180}, outputs: {'Alumina Solution': 120, 'Silica': 50}},
      {name: 'Aluminum Scrap', inputs: {'Alumina Solution': 240, 'Coal': 120}, outputs: {'Aluminum Scrap': 360, 'Water': 120}},
      {name: 'Fuel', inputs: {'Crude Oil': 60}, outputs: {'Fuel': 40, 'Polymer Resin': 30}},
      {name: 'Ionized Fuel', inputs: {'Rocket Fuel': 40, 'Power Shard': 2.5}, outputs: {'Ionized Fuel': 40, 'Compacted Coal': 5}},
      {name: 'Liquid Biofuel', inputs: {'Solid Biofuel': 90, 'Water': 45}, outputs: {'Liquid Biofuel': 60}},
      {name: 'Petroleum Coke', inputs: {'Heavy Oil Residue': 40}, outputs: {'Petroleum Coke': 120}},
      {name: 'Plastic', inputs: {'Crude Oil': 30}, outputs: {'Plastic': 20, 'Heavy Oil Residue': 10}},
      {name: 'Residual Fuel', inputs: {'Heavy Oil Residue': 60}, outputs: {'Fuel': 40}},
      {name: 'Residual Plastic', inputs: {'Polymer Resin': 60, 'Water': 20}, outputs: {'Plastic': 20}},
      {name: 'Residual Rubber', inputs: {'Polymer Resin': 40, 'Water': 40}, outputs: {'Rubber': 20}},
      {name: 'Rubber', inputs: {'Crude Oil': 30}, outputs: {'Rubber': 20, 'Heavy Oil Residue': 20}},
      {name: 'Smokeless Powder', inputs: {'Black Powder': 20, 'Heavy Oil Residue': 10}, outputs: {'Smokeless Powder': 20}},
      {name: 'Sulfuric Acid', inputs: {'Sulfur': 50, 'Water': 50}, outputs: {'Sulfuric Acid': 50}},
      {name: 'Coated Cable', inputs: {'Wire': 37.5, 'Heavy Oil Residue': 15}, outputs: {'Cable': 67.5}, isAlternate: true},
      {name: 'Diluted Packaged Fuel', inputs: {'Heavy Oil Residue': 30, 'Packaged Water': 60}, outputs: {'Packaged Fuel': 60}, isAlternate: true},
      {name: 'Electrode Aluminum Scrap', inputs: {'Alumina Solution': 180, 'Petroleum Coke': 60}, outputs: {'Aluminum Scrap': 300, 'Water': 105}, isAlternate: true},
      {name: 'Heavy Oil Residue', inputs: {'Crude Oil': 30}, outputs: {'Heavy Oil Residue': 40, 'Polymer Resin': 20}, isAlternate: true},
      {name: 'Leached Caterium Ingot', inputs: {'Caterium Ore': 54, 'Sulfuric Acid': 30}, outputs: {'Caterium Ingot': 36}, isAlternate: true},
      {name: 'Leached Copper Ingot', inputs: {'Copper Ore': 45, 'Sulfuric Acid': 25}, outputs: {'Copper Ingot': 110}, isAlternate: true},
      {name: 'Leached Iron Ingot', inputs: {'Iron Ore': 50, 'Sulfuric Acid': 10}, outputs: {'Iron Ingot': 100}, isAlternate: true},
      {name: 'Polyester Fabric', inputs: {'Polymer Resin': 30, 'Water': 30}, outputs: {'Fabric': 30}, isAlternate: true},
      {name: 'Polymer Resin', inputs: {'Crude Oil': 60}, outputs: {'Polymer Resin': 130, 'Heavy Oil Residue': 20}, isAlternate: true},
      {name: 'Pure Caterium Ingot', inputs: {'Caterium Ore': 24, 'Water': 24}, outputs: {'Caterium Ingot': 12}, isAlternate: true},
      {name: 'Pure Copper Ingot', inputs: {'Copper Ore': 15, 'Water': 10}, outputs: {'Copper Ingot': 37.5}, isAlternate: true},
      {name: 'Pure Iron Ingot', inputs: {'Iron Ore': 35, 'Water': 20}, outputs: {'Iron Ingot': 65}, isAlternate: true},
      {name: 'Pure Quartz Crystal', inputs: {'Raw Quartz': 67.5, 'Water': 37.5}, outputs: {'Quartz Crystal': 52.5}, isAlternate: true},
      {name: 'Quartz Purification', inputs: {'Raw Quartz': 120, 'Nitric Acid': 10}, outputs: {'Quartz Crystal': 75, 'Dissolved Silica': 60}, isAlternate: true},
      {name: 'Recycled Plastic', inputs: {'Rubber': 30, 'Fuel': 30}, outputs: {'Plastic': 60}, isAlternate: true},
      {name: 'Recycled Rubber', inputs: {'Plastic': 30, 'Fuel': 30}, outputs: {'Rubber': 60}, isAlternate: true},
      {name: 'Sloppy Alumina', inputs: {'Bauxite': 150, 'Water': 150}, outputs: {'Alumina Solution': 240}, isAlternate: true},
      {name: 'Sulfuric Uranium Extraction', inputs: {'Uranium': 20, 'Sulfuric Acid': 40}, outputs: {'Uranium Pellet': 60, 'Sulfuric Acid': 20}, isAlternate: true},
      {name: 'Turbofuel', inputs: {'Fuel': 22.5, 'Compacted Coal': 15}, outputs: {'Turbofuel': 18.75}},
      {name: 'Turbo Heavy Fuel', inputs: {'Heavy Oil Residue': 37.5, 'Compacted Coal': 30}, outputs: {'Turbofuel': 30}, isAlternate: true},
      {name: 'Wet Concrete', inputs: {'Limestone': 120, 'Water': 100}, outputs: {'Concrete': 80}, isAlternate: true}
    ],
    'Packager': [
      {name: 'Packaged Alumina Solution', inputs: {'Alumina Solution': 120, 'Empty Canister': 120}, outputs: {'Packaged Alumina Solution': 120}},
      {name: 'Packaged Fuel', inputs: {'Fuel': 40, 'Empty Canister': 40}, outputs: {'Packaged Fuel': 40}},
      {name: 'Packaged Heavy Oil Residue', inputs: {'Heavy Oil Residue': 30, 'Empty Canister': 30}, outputs: {'Packaged Heavy Oil Residue': 30}},
      {name: 'Packaged Ionized Fuel', inputs: {'Ionized Fuel': 80, 'Empty Fluid Tank': 40}, outputs: {'Packaged Ionized Fuel': 40}},
      {name: 'Packaged Liquid Biofuel', inputs: {'Liquid Biofuel': 40, 'Empty Canister': 40}, outputs: {'Packaged Liquid Biofuel': 40}},
      {name: 'Packaged Nitric Acid', inputs: {'Nitric Acid': 30, 'Empty Fluid Tank': 30}, outputs: {'Packaged Nitric Acid': 30}},
      {name: 'Packaged Nitrogen Gas', inputs: {'Nitrogen Gas': 240, 'Empty Fluid Tank': 60}, outputs: {'Packaged Nitrogen Gas': 60}},
      {name: 'Packaged Oil', inputs: {'Crude Oil': 30, 'Empty Canister': 30}, outputs: {'Packaged Oil': 30}},
      {name: 'Packaged Rocket Fuel', inputs: {'Rocket Fuel': 120, 'Empty Fluid Tank': 60}, outputs: {'Packaged Rocket Fuel': 60}},
      {name: 'Packaged Sulfuric Acid', inputs: {'Sulfuric Acid': 40, 'Empty Canister': 40}, outputs: {'Packaged Sulfuric Acid': 40}},
      {name: 'Packaged Turbofuel', inputs: {'Turbofuel': 20, 'Empty Canister': 20}, outputs: {'Packaged Turbofuel': 20}},
      {name: 'Packaged Water', inputs: {'Water': 60, 'Empty Canister': 60}, outputs: {'Packaged Water': 60}},
      {name: 'Unpackage Alumina Solution', inputs: {'Packaged Alumina Solution': 120}, outputs: {'Alumina Solution': 120, 'Empty Canister': 120}},
      {name: 'Unpackage Fuel', inputs: {'Packaged Fuel': 60}, outputs: {'Fuel': 60, 'Empty Canister': 60}},
      {name: 'Unpackage Heavy Oil Residue', inputs: {'Packaged Heavy Oil Residue': 20}, outputs: {'Heavy Oil Residue': 20, 'Empty Canister': 20}},
      {name: 'Unpackage Ionized Fuel', inputs: {'Packaged Ionized Fuel': 40}, outputs: {'Ionized Fuel': 80, 'Empty Fluid Tank': 40}},
      {name: 'Unpackage Liquid Biofuel', inputs: {'Packaged Liquid Biofuel': 60}, outputs: {'Liquid Biofuel': 60, 'Empty Canister': 60}},
      {name: 'Unpackage Nitric Acid', inputs: {'Packaged Nitric Acid': 20}, outputs: {'Nitric Acid': 20, 'Empty Fluid Tank': 20}},
      {name: 'Unpackage Nitrogen Gas', inputs: {'Packaged Nitrogen Gas': 60}, outputs: {'Nitrogen Gas': 240, 'Empty Fluid Tank': 60}},
      {name: 'Unpackage Oil', inputs: {'Packaged Oil': 60}, outputs: {'Crude Oil': 60, 'Empty Canister': 60}},
      {name: 'Unpackage Rocket Fuel', inputs: {'Packaged Rocket Fuel': 60}, outputs: {'Rocket Fuel': 120, 'Empty Fluid Tank': 60}},
      {name: 'Unpackage Sulfuric Acid', inputs: {'Packaged Sulfuric Acid': 60}, outputs: {'Sulfuric Acid': 60, 'Empty Canister': 60}},
      {name: 'Unpackage Turbofuel', inputs: {'Packaged Turbofuel': 20}, outputs: {'Turbofuel': 20, 'Empty Canister': 20}},
      {name: 'Unpackage Water', inputs: {'Packaged Water': 120}, outputs: {'Water': 120, 'Empty Canister': 120}}
    ],
    'Blender': [
      {name: 'Battery', inputs: {'Sulfuric Acid': 50, 'Alumina Solution': 40, 'Aluminum Casing': 20}, outputs: {'Battery': 20, 'Water': 30}},
      {name: 'Biochemical Sculptor', inputs: {'Assembly Director System': 0.5, 'Ficsite Trigon': 40, 'Water': 10}, outputs: {'Biochemical Sculptor': 2}},
      {name: 'Cooling System', inputs: {'Heat Sink': 12, 'Rubber': 12, 'Water': 30, 'Nitrogen Gas': 150}, outputs: {'Cooling System': 6}},
      {name: 'Encased Uranium Cell', inputs: {'Uranium': 50, 'Concrete': 15, 'Sulfuric Acid': 40}, outputs: {'Encased Uranium Cell': 25, 'Sulfuric Acid': 10}},
      {name: 'Fused Modular Frame', inputs: {'Heavy Modular Frame': 1.5, 'Aluminum Casing': 75, 'Nitrogen Gas': 37.5}, outputs: {'Fused Modular Frame': 1.5}},
      {name: 'Nitric Acid', inputs: {'Nitrogen Gas': 120, 'Water': 30, 'Iron Plate': 10}, outputs: {'Nitric Acid': 30}},
      {name: 'Non-Fissile Uranium', inputs: {'Uranium Waste': 37.5, 'Silica': 25, 'Nitric Acid': 15, 'Sulfuric Acid': 15}, outputs: {'Non-Fissile Uranium': 50, 'Water': 15}},
      {name: 'Rocket Fuel', inputs: {'Turbofuel': 60, 'Nitric Acid': 10}, outputs: {'Rocket Fuel': 100, 'Compacted Coal': 10}},
      {name: 'Turbo Rifle Ammo', inputs: {'Rifle Ammo': 125, 'Aluminum Casing': 15, 'Turbofuel': 15}, outputs: {'Turbo Rifle Ammo': 250}},
      {name: 'Cooling Device', inputs: {'Heat Sink': 10, 'Motor': 2.5, 'Nitrogen Gas': 60}, outputs: {'Cooling System': 5}, isAlternate: true},
      {name: 'Diluted Fuel', inputs: {'Heavy Oil Residue': 50, 'Water': 100}, outputs: {'Fuel': 100}, isAlternate: true},
      {name: 'Distilled Silica', inputs: {'Dissolved Silica': 120, 'Limestone': 50, 'Water': 100}, outputs: {'Silica': 270, 'Water': 80}, isAlternate: true},
      {name: 'Fertile Uranium', inputs: {'Uranium': 25, 'Uranium Waste': 25, 'Nitric Acid': 15, 'Sulfuric Acid': 25}, outputs: {'Non-Fissile Uranium': 100, 'Water': 40}, isAlternate: true},
      {name: 'Heat-Fused Frame', inputs: {'Heavy Modular Frame': 3, 'Aluminum Ingot': 150, 'Nitric Acid': 24, 'Fuel': 30}, outputs: {'Fused Modular Frame': 3}, isAlternate: true},
      {name: 'Instant Scrap', inputs: {'Bauxite': 150, 'Coal': 100, 'Sulfuric Acid': 50, 'Water': 60}, outputs: {'Aluminum Scrap': 300, 'Water': 50}, isAlternate: true}
    ],
    'Particle Accelerator': [
      {name: 'Dark Matter Crystal', inputs: {'Diamonds': 30, 'Dark Matter Residue': 150}, outputs: {'Dark Matter Crystal': 30}},
      {name: 'Diamonds', inputs: {'Coal': 600}, outputs: {'Diamonds': 30}},
      {name: 'Ficsonium', inputs: {'Plutonium Waste': 10, 'Singularity Cell': 10, 'Dark Matter Residue': 200}, outputs: {'Ficsonium': 10}},
      {name: 'Nuclear Pasta', inputs: {'Copper Powder': 100, 'Pressure Conversion Cube': 0.5}, outputs: {'Nuclear Pasta': 0.5}},
      {name: 'Plutonium Pellet', inputs: {'Non-Fissile Uranium': 100, 'Uranium Waste': 25}, outputs: {'Plutonium Pellet': 30}},
      {name: 'Cloudy Diamonds', inputs: {'Coal': 240, 'Limestone': 480}, outputs: {'Diamonds': 20}, isAlternate: true},
      {name: 'Dark Matter Crystallization', inputs: {'Dark Matter Residue': 200}, outputs: {'Dark Matter Crystal': 20}, isAlternate: true},
      {name: 'Dark Matter Trap', inputs: {'Time Crystal': 30, 'Dark Matter Residue': 150}, outputs: {'Dark Matter Crystal': 60}, isAlternate: true},
      {name: 'Instant Plutonium Cell', inputs: {'Non-Fissile Uranium': 75, 'Aluminum Casing': 10}, outputs: {'Encased Plutonium Cell': 10}, isAlternate: true},
      {name: 'Oil-Based Diamonds', inputs: {'Crude Oil': 200}, outputs: {'Diamonds': 40}, isAlternate: true},
      {name: 'Petroleum Diamonds', inputs: {'Petroleum Coke': 720}, outputs: {'Diamonds': 30}, isAlternate: true},
      {name: 'Turbo Diamonds', inputs: {'Coal': 600, 'Packaged Turbofuel': 40}, outputs: {'Diamonds': 60}, isAlternate: true}
    ],
    'Converter': [
      {name: 'Bauxite (Caterium)', inputs: {'Reanimated SAM': 10, 'Caterium Ore': 150}, outputs: {'Bauxite': 120}},
      {name: 'Bauxite (Copper)', inputs: {'Reanimated SAM': 10, 'Copper Ore': 180}, outputs: {'Bauxite': 120}},
      {name: 'Caterium Ore (Copper)', inputs: {'Reanimated SAM': 10, 'Copper Ore': 150}, outputs: {'Caterium Ore': 120}},
      {name: 'Caterium Ore (Quartz)', inputs: {'Reanimated SAM': 10, 'Raw Quartz': 120}, outputs: {'Caterium Ore': 120}},
      {name: 'Coal (Iron)', inputs: {'Reanimated SAM': 10, 'Iron Ore': 180}, outputs: {'Coal': 120}},
      {name: 'Coal (Limestone)', inputs: {'Reanimated SAM': 10, 'Limestone': 360}, outputs: {'Coal': 120}},
      {name: 'Copper Ore (Quartz)', inputs: {'Reanimated SAM': 10, 'Raw Quartz': 100}, outputs: {'Copper Ore': 120}},
      {name: 'Copper Ore (Sulfur)', inputs: {'Reanimated SAM': 10, 'Sulfur': 120}, outputs: {'Copper Ore': 120}},
      {name: 'Dark Matter Residue', inputs: {'Reanimated SAM': 50}, outputs: {'Dark Matter Residue': 100}},
      {name: 'Excited Photonic Matter', inputs: {}, outputs: {'Excited Photonic Matter': 200}},
      {name: 'Ficsite Ingot (Aluminum)', inputs: {'Reanimated SAM': 60, 'Aluminum Ingot': 120}, outputs: {'Ficsite Ingot': 30}},
      {name: 'Ficsite Ingot (Caterium)', inputs: {'Reanimated SAM': 45, 'Caterium Ingot': 60}, outputs: {'Ficsite Ingot': 15}},
      {name: 'Ficsite Ingot (Iron)', inputs: {'Reanimated SAM': 40, 'Iron Ingot': 240}, outputs: {'Ficsite Ingot': 10}},
      {name: 'Iron Ore (Limestone)', inputs: {'Reanimated SAM': 10, 'Limestone': 240}, outputs: {'Iron Ore': 120}},
      {name: 'Limestone (Sulfur)', inputs: {'Reanimated SAM': 10, 'Sulfur': 20}, outputs: {'Limestone': 120}},
      {name: 'Nitrogen Gas (Bauxite)', inputs: {'Reanimated SAM': 10, 'Bauxite': 100}, outputs: {'Nitrogen Gas': 120}},
      {name: 'Nitrogen Gas (Caterium)', inputs: {'Reanimated SAM': 10, 'Caterium Ore': 120}, outputs: {'Nitrogen Gas': 120}},
      {name: 'Raw Quartz (Bauxite)', inputs: {'Reanimated SAM': 10, 'Bauxite': 100}, outputs: {'Raw Quartz': 120}},
      {name: 'Raw Quartz (Coal)', inputs: {'Reanimated SAM': 10, 'Coal': 240}, outputs: {'Raw Quartz': 120}},
      {name: 'Sulfur (Coal)', inputs: {'Reanimated SAM': 10, 'Coal': 200}, outputs: {'Sulfur': 120}},
      {name: 'Sulfur (Iron)', inputs: {'Reanimated SAM': 10, 'Iron Ore': 300}, outputs: {'Sulfur': 120}},
      {name: 'Time Crystal', inputs: {'Diamonds': 12}, outputs: {'Time Crystal': 6}},
      {name: 'Uranium Ore (Bauxite)', inputs: {'Reanimated SAM': 10, 'Bauxite': 480}, outputs: {'Uranium': 120}},
      {name: 'Dark-Ion Fuel', inputs: {'Packaged Rocket Fuel': 240, 'Dark Matter Crystal': 80}, outputs: {'Ionized Fuel': 200, 'Compacted Coal': 40}, isAlternate: true},
      {name: 'Pink Diamonds', inputs: {'Coal': 120, 'Quartz Crystal': 45}, outputs: {'Diamonds': 15}, isAlternate: true}
    ],
    'Quantum Encoder': [
      {name: 'AI Expansion Server', inputs: {'Magnetic Field Generator': 4, 'Neural-Quantum Processor': 4, 'Superposition Oscillator': 4, 'Excited Photonic Matter': 100}, outputs: {'AI Expansion Server': 4, 'Dark Matter Residue': 100}},
      {name: 'Alien Power Matrix', inputs: {'SAM Fluctuator': 12.5, 'Power Shard': 7.5, 'Superposition Oscillator': 7.5, 'Excited Photonic Matter': 60}, outputs: {'Alien Power Matrix': 2.5, 'Dark Matter Residue': 60}},
      {name: 'Ficsonium Fuel Rod', inputs: {'Ficsonium': 5, 'Electromagnetic Control Rod': 5, 'Ficsite Trigon': 100, 'Excited Photonic Matter': 50}, outputs: {'Ficsonium Fuel Rod': 2.5, 'Dark Matter Residue': 50}},
      {name: 'Neural-Quantum Processor', inputs: {'Time Crystal': 15, 'Supercomputer': 3, 'Ficsite Trigon': 45, 'Excited Photonic Matter': 75}, outputs: {'Neural-Quantum Processor': 3, 'Dark Matter Residue': 75}},
      {name: 'Superposition Oscillator', inputs: {'Dark Matter Crystal': 30, 'Crystal Oscillator': 5, 'Alclad Aluminum Sheet': 45, 'Excited Photonic Matter': 125}, outputs: {'Superposition Oscillator': 5, 'Dark Matter Residue': 125}},
      {name: 'Synthetic Power Shard', inputs: {'Time Crystal': 10, 'Dark Matter Crystal': 10, 'Quartz Crystal': 60, 'Excited Photonic Matter': 60}, outputs: {'Power Shard': 5, 'Dark Matter Residue': 60}}
    ],
    'Miner Mk.1': [
      {name: 'Iron Ore', inputs: {}, outputs: {'Iron Ore': 60}},
      {name: 'Copper Ore', inputs: {}, outputs: {'Copper Ore': 60}},
      {name: 'Limestone', inputs: {}, outputs: {'Limestone': 60}},
      {name: 'Coal', inputs: {}, outputs: {'Coal': 60}},
      {name: 'Caterium Ore', inputs: {}, outputs: {'Caterium Ore': 60}},
      {name: 'Sulfur', inputs: {}, outputs: {'Sulfur': 60}},
      {name: 'Raw Quartz', inputs: {}, outputs: {'Raw Quartz': 60}},
      {name: 'Bauxite', inputs: {}, outputs: {'Bauxite': 60}},
      {name: 'Uranium', inputs: {}, outputs: {'Uranium': 60}},
      {name: 'SAM', inputs: {}, outputs: {'SAM': 60}}
    ],
    'Miner Mk.2': [
      {name: 'Iron Ore', inputs: {}, outputs: {'Iron Ore': 120}},
      {name: 'Copper Ore', inputs: {}, outputs: {'Copper Ore': 120}},
      {name: 'Limestone', inputs: {}, outputs: {'Limestone': 120}},
      {name: 'Coal', inputs: {}, outputs: {'Coal': 120}},
      {name: 'Caterium Ore', inputs: {}, outputs: {'Caterium Ore': 120}},
      {name: 'Sulfur', inputs: {}, outputs: {'Sulfur': 120}},
      {name: 'Raw Quartz', inputs: {}, outputs: {'Raw Quartz': 120}},
      {name: 'Bauxite', inputs: {}, outputs: {'Bauxite': 120}},
      {name: 'Uranium', inputs: {}, outputs: {'Uranium': 120}},
      {name: 'SAM', inputs: {}, outputs: {'SAM': 120}}
    ],
    'Miner Mk.3': [
      {name: 'Iron Ore', inputs: {}, outputs: {'Iron Ore': 240}},
      {name: 'Copper Ore', inputs: {}, outputs: {'Copper Ore': 240}},
      {name: 'Limestone', inputs: {}, outputs: {'Limestone': 240}},
      {name: 'Coal', inputs: {}, outputs: {'Coal': 240}},
      {name: 'Caterium Ore', inputs: {}, outputs: {'Caterium Ore': 240}},
      {name: 'Sulfur', inputs: {}, outputs: {'Sulfur': 240}},
      {name: 'Raw Quartz', inputs: {}, outputs: {'Raw Quartz': 240}},
      {name: 'Bauxite', inputs: {}, outputs: {'Bauxite': 240}},
      {name: 'Uranium', inputs: {}, outputs: {'Uranium': 240}},
      {name: 'SAM', inputs: {}, outputs: {'SAM': 240}}
    ],
    'Water Extractor': [
      {name: 'Water', inputs: {}, outputs: {'Water': 120}}
    ],
    'Oil Extractor': [
      {name: 'Crude Oil', inputs: {}, outputs: {'Crude Oil': 120}}
    ],
    'Resource Well Extractor': [
      {name: 'Nitrogen Gas', inputs: {}, outputs: {'Nitrogen Gas': 60}}
    ],
    'Biomass Burner': [
      {name: 'Biomass', inputs: {'Biomass': 30}, outputs: {}},
      {name: 'Solid Biofuel', inputs: {'Solid Biofuel': 15}, outputs: {}},
      {name: 'Leaves', inputs: {'Leaves': 120}, outputs: {}},
      {name: 'Wood', inputs: {'Wood': 60}, outputs: {}}
    ],
    'Coal Generator': [
      {name: 'Coal', inputs: {'Coal': 15, 'Water': 45}, outputs: {}},
      {name: 'Compacted Coal', inputs: {'Compacted Coal': 7.14, 'Water': 45}, outputs: {}},
      {name: 'Petroleum Coke', inputs: {'Petroleum Coke': 25, 'Water': 45}, outputs: {}}
    ],
    'Fuel Generator': [
      {name: 'Fuel', inputs: {'Fuel': 20}, outputs: {}},
      {name: 'Liquid Biofuel', inputs: {'Liquid Biofuel': 20}, outputs: {}},
      {name: 'Turbofuel', inputs: {'Turbofuel': 7.5}, outputs: {}},
      {name: 'Rocket Fuel', inputs: {'Rocket Fuel': 4.17}, outputs: {}},
      {name: 'Ionized Fuel', inputs: {'Ionized Fuel': 3}, outputs: {}}
    ],
    'Geothermal Generator': [
      {name: 'Thermal', inputs: {}, outputs: {}}
    ],
    'Nuclear Power Plant': [
      {name: 'Uranium Fuel Rod', inputs: {'Uranium Fuel Rod': 0.2, 'Water': 240}, outputs: {'Uranium Waste': 10}},
      {name: 'Plutonium Fuel Rod', inputs: {'Plutonium Fuel Rod': 0.1, 'Water': 240}, outputs: {'Plutonium Waste': 1}},
      {name: 'Ficsonium Fuel Rod', inputs: {'Ficsonium Fuel Rod': 1, 'Water': 240}, outputs: {}}
    ]
  }
};
